/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabacaria.views;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tabacaria.models.Estoque;
import tabacaria.models.EstoqueTableModel;
import tabacaria.models.Item;
import tabacaria.models.Produto;
import tabacaria.models.Compra;
import tabacaria.models.CompraTableModel;

/**
 *
 * @author pedro
 */
public class AlteracaoQuantidadeCompra extends javax.swing.JFrame {

    private Item item;
    private Compra compra;
    private CompraTableModel compraTM;
    private int flag;
    private String oldName;
    public AlteracaoQuantidadeCompra() {
        initComponents();
    }

    AlteracaoQuantidadeCompra(Item i, Compra v, CompraTableModel vtm, int flag) {
        this.item = i;
        this.compra = v;
        this.compraTM = vtm;
        this.setDefaultCloseOperation( JFrame.HIDE_ON_CLOSE );
        this.setSize(360, 295);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.oldName = i.getProduto().getNome();
        
        initComponents();
        
        NomeTxtField.setText(i.getProduto().getNome());

        Quantidade.setValue(i.getQuantidade());
        
        if(flag == 0){
            ExcluirBtn.setVisible(false);
            SaveBtn.setText("Adicionar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormProdutoPanel = new javax.swing.JPanel();
        NomeTxtField = new javax.swing.JTextField();
        NomeLbl = new javax.swing.JLabel();
        ProdutoTxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        QuantidadeLbl = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        CancelaBtn = new javax.swing.JButton();
        Quantidade = new javax.swing.JSpinner();
        ExcluirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(354, 274));

        FormProdutoPanel.setBackground(new java.awt.Color(255, 255, 255));
        FormProdutoPanel.setMinimumSize(new java.awt.Dimension(354, 274));
        FormProdutoPanel.setPreferredSize(new java.awt.Dimension(354, 274));

        NomeTxtField.setEditable(false);
        NomeTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        NomeLbl.setText("Nome");

        ProdutoTxt.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        ProdutoTxt.setForeground(new java.awt.Color(255, 204, 51));
        ProdutoTxt.setText("Produto");

        jSeparator1.setForeground(new java.awt.Color(255, 204, 0));

        QuantidadeLbl.setText("Quantidade");

        SaveBtn.setText("Salvar");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        CancelaBtn.setText("Cancelar");
        CancelaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaBtnActionPerformed(evt);
            }
        });

        Quantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        ExcluirBtn.setText("Remover");
        ExcluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormProdutoPanelLayout = new javax.swing.GroupLayout(FormProdutoPanel);
        FormProdutoPanel.setLayout(FormProdutoPanelLayout);
        FormProdutoPanelLayout.setHorizontalGroup(
            FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NomeTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(NomeLbl)
                            .addComponent(ProdutoTxt)))
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(QuantidadeLbl)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                                .addComponent(CancelaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)
                                .addComponent(SaveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        FormProdutoPanelLayout.setVerticalGroup(
            FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                .addComponent(ProdutoTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeLbl)
                .addGap(4, 4, 4)
                .addComponent(NomeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuantidadeLbl)
                .addGap(9, 9, 9)
                .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormProdutoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormProdutoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaBtnActionPerformed
        dispose();
    }//GEN-LAST:event_CancelaBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        
        Produto p;
        p = new Produto(NomeTxtField.getText(), item.getProduto().getDescricao(), item.getProduto().getpCompra(), item.getProduto().getpVenda());
        Item i = new Item(p, (Integer) Quantidade.getValue());
        
        this.compra.incluirItem(i);
        this.compraTM.refresh();
        dispose();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ExcluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBtnActionPerformed
        
        if(JOptionPane.showConfirmDialog(null, "Tem que deseja excluir este produto?") == 0){ //se clicar em confirmar
            compra.removerItem(item);
            this.compraTM.refresh();
            this.dispose();
        }
        
    }//GEN-LAST:event_ExcluirBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteracaoQuantidadeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteracaoQuantidadeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteracaoQuantidadeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteracaoQuantidadeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlteracaoQuantidadeCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelaBtn;
    private javax.swing.JButton ExcluirBtn;
    private javax.swing.JPanel FormProdutoPanel;
    private javax.swing.JLabel NomeLbl;
    private javax.swing.JTextField NomeTxtField;
    private javax.swing.JLabel ProdutoTxt;
    private javax.swing.JSpinner Quantidade;
    private javax.swing.JLabel QuantidadeLbl;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
