/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabacaria.views;

import helpers.Arquivo;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import org.json.simple.parser.ParseException;
import tabacaria.models.Caixa;
import tabacaria.models.CaixaTableModel;
import tabacaria.models.Categoria;
import tabacaria.models.CategoriaTableModel;
import tabacaria.models.Cliente;
import tabacaria.models.ClienteTableModel;
import tabacaria.models.Estoque;
import tabacaria.models.EstoqueTableModel;
import tabacaria.models.Fornecedor;
import tabacaria.models.FornecedorTableModel;
import tabacaria.models.Funcionario;
import tabacaria.models.FuncionarioTableModel;

/**
 *
 * @author pedro
 */
public class Configuracoes extends javax.swing.JFrame {

    private final Estoque estoque;
    private final EstoqueTableModel estoqueTM;
    private final ArrayList<Cliente> clientes;
    private final ClienteTableModel clienteTM;
    private final ArrayList<Categoria> categorias;
    private final CategoriaTableModel categoriaTM;
    private final ArrayList<Fornecedor> fornecedores;
    private final FornecedorTableModel fornecedorTM;
    private final ArrayList<Funcionario> funcionarios;
    private final FuncionarioTableModel funcionarioTM;
    private final Caixa caixa;
    private final CaixaTableModel caixaTM;
    private final JFileChooser jfc;
    private final Funcionario funcLogado;

    /**
     * Creates new form Configuracoes
     */
    public Configuracoes(Estoque estoque, ArrayList<Cliente> clientes, ArrayList<Categoria> categorias, ArrayList<Fornecedor> fornecedores, ArrayList<Funcionario> funcionarios, Caixa caixa
        , EstoqueTableModel estoqueTM, ClienteTableModel clienteTM, CategoriaTableModel categoriaTM, FornecedorTableModel fornecedorTM, FuncionarioTableModel funcionarioTM
            , CaixaTableModel caixaTM, Funcionario funcLogado ) {
        
        this.estoque = estoque;
        this.estoqueTM = estoqueTM;
        
        
        this.clientes = clientes;
        this.clienteTM = clienteTM;
        
        
        this.categorias = categorias;
        this.categoriaTM = categoriaTM;
        
        
        this.fornecedores = fornecedores;
        this.fornecedorTM = fornecedorTM;
        
        
        
        this.funcionarios = funcionarios;
        this.funcionarioTM = funcionarioTM;
        
        
        this.caixa = caixa;
        this.caixaTM = caixaTM;
        
        this.funcLogado = funcLogado;
        
        this.jfc = new JFileChooser("./");
        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Json files", "json");
        jfc.addChoosableFileFilter(filter);
        
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Configuracoes = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ConfigTxt = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        LoadBtn = new javax.swing.JButton();
        ChangePassBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Configuracoes.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(255, 204, 0));

        ConfigTxt.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        ConfigTxt.setForeground(new java.awt.Color(255, 204, 51));
        ConfigTxt.setText("Configurações");

        SaveBtn.setBackground(new java.awt.Color(255, 255, 255));
        SaveBtn.setText("Salvar Configuração Atual");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        LoadBtn.setBackground(new java.awt.Color(255, 255, 255));
        LoadBtn.setText("Recuperar Configuração Antiga");
        LoadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadBtnActionPerformed(evt);
            }
        });

        ChangePassBtn.setBackground(new java.awt.Color(255, 255, 255));
        ChangePassBtn.setText("Alterar Senha");
        ChangePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setText("Desconectar");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelBtn.setText("Cancelar");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfiguracoesLayout = new javax.swing.GroupLayout(Configuracoes);
        Configuracoes.setLayout(ConfiguracoesLayout);
        ConfiguracoesLayout.setHorizontalGroup(
            ConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfiguracoesLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(ConfigTxt)
                .addGap(0, 64, Short.MAX_VALUE))
            .addGroup(ConfiguracoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(LoadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(ChangePassBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(LogoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConfiguracoesLayout.setVerticalGroup(
            ConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfiguracoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConfigTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveBtn)
                .addGap(18, 18, 18)
                .addComponent(LoadBtn)
                .addGap(18, 18, 18)
                .addComponent(ChangePassBtn)
                .addGap(18, 18, 18)
                .addComponent(LogoutBtn)
                .addGap(18, 18, 18)
                .addComponent(CancelBtn)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Configuracoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Configuracoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        
        int returnValue = jfc.showOpenDialog(null);
        String path = "data/tabacaria.json";
        if (returnValue == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jfc.getSelectedFile();
                path = selectedFile.getAbsolutePath();
        }
        
        try {
            Arquivo.save(categorias, clientes, funcionarios, fornecedores, estoque, caixa, path);
        } catch (IOException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void LoadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadBtnActionPerformed
        int returnValue = jfc.showOpenDialog(null);
        String path = "data/tabacaria.json";
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jfc.getSelectedFile();
                path = selectedFile.getAbsolutePath();
        }
        
        try {
            Arquivo.load(categorias, clientes, funcionarios, fornecedores, estoque, caixa, path);
        } catch (ParseException ex) {
            Logger.getLogger(Configuracoes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Configuracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        estoqueTM.refresh();
        clienteTM.refresh();
        categoriaTM.refresh();
        funcionarioTM.refresh();
        fornecedorTM.refresh();
        caixaTM.refresh();
        
        dispose();
        
    }//GEN-LAST:event_LoadBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void ChangePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassBtnActionPerformed
        FormularioFuncionario ffunc = new FormularioFuncionario(funcLogado, funcionarios, funcionarioTM, 2);
    }//GEN-LAST:event_ChangePassBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_LogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Configuracoes().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton ChangePassBtn;
    private javax.swing.JLabel ConfigTxt;
    private javax.swing.JPanel Configuracoes;
    private javax.swing.JButton LoadBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
