/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabacaria.views;

import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.TableRowSorter;
import tabacaria.models.Categoria;
import tabacaria.models.CategoriaTableModel;


/**
 *
 * @author pedro
 */
public class ControleCategorias extends javax.swing.JFrame {

    /**
     * Creates new form Categorias
     */
    
    private  ArrayList<Categoria> categorias;
    private  CategoriaTableModel categoriaTM;
    private  TableRowSorter<CategoriaTableModel> sorterCategorias;


    ControleCategorias( ArrayList<Categoria> categorias, CategoriaTableModel categoriaTM) {
        this.categorias = categorias;
        this.categoriaTM = new CategoriaTableModel(categorias);
        this.sorterCategorias = new TableRowSorter<>(categoriaTM);
        
        initComponents();
    }

    private ControleCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormCategoriaPane = new javax.swing.JPanel();
        CategoriaLabel = new javax.swing.JLabel();
        CategoriasScrollPane = new javax.swing.JScrollPane();
        CategoriasJTable = new javax.swing.JTable();
        CategoriaSearchTxtField = new javax.swing.JTextField();
        CategoriaSearchBtn = new javax.swing.JButton();
        CategoriaAddBtn = new javax.swing.JButton();
        Categorias = new javax.swing.JLabel();
        SeparatorCategorias = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FormCategoriaPane.setBackground(new java.awt.Color(255, 255, 255));
        FormCategoriaPane.setMinimumSize(new java.awt.Dimension(354, 274));

        CategoriaLabel.setText("Categoria:");

        CategoriasJTable.setModel(categoriaTM);
        CategoriasJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriasJTableMouseClicked(evt);
            }
        });
        CategoriasScrollPane.setViewportView(CategoriasJTable);

        CategoriaSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/search.png"))); // NOI18N
        CategoriaSearchBtn.setText("Buscar");
        CategoriaSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaSearchBtnActionPerformed(evt);
            }
        });

        CategoriaAddBtn.setBackground(new java.awt.Color(255, 255, 255));
        CategoriaAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/add.png"))); // NOI18N
        CategoriaAddBtn.setText("Nova Categoria");
        CategoriaAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaAddBtnActionPerformed(evt);
            }
        });

        Categorias.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 48)); // NOI18N
        Categorias.setForeground(new java.awt.Color(255, 204, 51));
        Categorias.setText("Categorias");

        SeparatorCategorias.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout FormCategoriaPaneLayout = new javax.swing.GroupLayout(FormCategoriaPane);
        FormCategoriaPane.setLayout(FormCategoriaPaneLayout);
        FormCategoriaPaneLayout.setHorizontalGroup(
            FormCategoriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormCategoriaPaneLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(Categorias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FormCategoriaPaneLayout.createSequentialGroup()
                .addGroup(FormCategoriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormCategoriaPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CategoriaAddBtn))
                    .addGroup(FormCategoriaPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CategoriaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CategoriaSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 170, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormCategoriaPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CategoriasScrollPane)))
                .addContainerGap())
            .addGroup(FormCategoriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FormCategoriaPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(FormCategoriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SeparatorCategorias)
                        .addGroup(FormCategoriaPaneLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(CategoriaSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        FormCategoriaPaneLayout.setVerticalGroup(
            FormCategoriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormCategoriaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Categorias)
                .addGap(35, 35, 35)
                .addGroup(FormCategoriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoriaSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoriaLabel))
                .addGap(17, 17, 17)
                .addComponent(CategoriasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CategoriaAddBtn)
                .addContainerGap())
            .addGroup(FormCategoriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FormCategoriaPaneLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(SeparatorCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(CategoriaSearchBtn)
                    .addContainerGap(488, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormCategoriaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormCategoriaPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoriasJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriasJTableMouseClicked
        if (2 == evt.getClickCount()) {
        
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            alterarCategoria(row);
        }
    }//GEN-LAST:event_CategoriasJTableMouseClicked

    private void CategoriaSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaSearchBtnActionPerformed

    private void CategoriaAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaAddBtnActionPerformed
        addCategoria();
    }//GEN-LAST:event_CategoriaAddBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new ControleCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CategoriaAddBtn;
    private javax.swing.JLabel CategoriaLabel;
    private javax.swing.JButton CategoriaSearchBtn;
    private javax.swing.JTextField CategoriaSearchTxtField;
    private javax.swing.JLabel Categorias;
    private javax.swing.JTable CategoriasJTable;
    private javax.swing.JScrollPane CategoriasScrollPane;
    private javax.swing.JPanel FormCategoriaPane;
    private javax.swing.JSeparator SeparatorCategorias;
    // End of variables declaration//GEN-END:variables

    private void addCategoria() {
        Categoria categoria = new Categoria();
        
        FormularioCategoria fc = new FormularioCategoria(categoria, categorias, categoriaTM, 0);
    }

    private void alterarCategoria(int row) {
        FormularioCategoria fp = new FormularioCategoria(categorias.get(row), categorias, categoriaTM, 1);

    }
}
