/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabacaria.views;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tabacaria.models.Funcionario;
import tabacaria.models.FuncionarioTableModel;
import tabacaria.models.Data;
import tabacaria.models.Estoque;
import tabacaria.models.EstoqueTableModel;
import tabacaria.models.Item;
import tabacaria.models.Produto;

/**
 *
 * @author pedro
 */
public class FormularioFuncionario extends javax.swing.JFrame {

    private Funcionario funcionario;
    ArrayList<Funcionario> funcionarios;
    FuncionarioTableModel funcionarioTM;
    private int flag;
    private String oldName;
    public FormularioFuncionario() {
        initComponents();
    }

    FormularioFuncionario(Funcionario f, ArrayList<Funcionario> funcionarios, FuncionarioTableModel ctm, int flag) { //flag diz se é pra adicionar ou atualizar
        this.funcionario = f;
        this.funcionarios = funcionarios;
        this.funcionarioTM = ctm;
        this.flag = flag;
        this.setDefaultCloseOperation( JFrame.HIDE_ON_CLOSE );
        this.setSize(360, 295);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.oldName = f.getNome();
        
        initComponents();
        
        if(flag >= 1){ //se for para alterar
            NomeTxtField.setText(f.getNome());
            CPFTxtField.setText(String.valueOf(f.getCPF()));
            SalarioSpinner.setValue(f.getSalario());
            FuncaoCombo.setSelectedIndex(f.getAcesso());
            SenhaField.setText(f.getSenha());
            

        }
        if(flag == 1){
            SenhaField.setEnabled(false); // se o código for 1, um gerente está vendo outro funcionário e nao pode mudar sua senha
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoriaCombo = new javax.swing.JComboBox<>();
        FormProdutoPanel = new javax.swing.JPanel();
        NomeTxtField = new javax.swing.JTextField();
        NomeLbl = new javax.swing.JLabel();
        FuncionarioTxt = new javax.swing.JLabel();
        CPFLbl = new javax.swing.JLabel();
        SeparatorFuncionarioForm = new javax.swing.JSeparator();
        SaveBtn = new javax.swing.JButton();
        CancelaBtn = new javax.swing.JButton();
        ExcluirBtn = new javax.swing.JButton();
        CPFTxtField = new javax.swing.JTextField();
        SalarioLbl = new javax.swing.JLabel();
        FuncaoCombo = new javax.swing.JComboBox<>();
        FuncaoLbl = new javax.swing.JLabel();
        SalarioSpinner = new javax.swing.JSpinner();
        SenhaLbl = new javax.swing.JLabel();
        SenhaField = new javax.swing.JPasswordField();

        CategoriaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria Teste" }));
        CategoriaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaComboActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(354, 274));

        FormProdutoPanel.setBackground(new java.awt.Color(255, 255, 255));
        FormProdutoPanel.setMinimumSize(new java.awt.Dimension(354, 274));
        FormProdutoPanel.setPreferredSize(new java.awt.Dimension(354, 274));

        NomeTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        NomeLbl.setText("Nome");

        FuncionarioTxt.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        FuncionarioTxt.setForeground(new java.awt.Color(255, 204, 51));
        FuncionarioTxt.setText("Funcionário");

        CPFLbl.setText("CPF");

        SeparatorFuncionarioForm.setForeground(new java.awt.Color(255, 204, 0));

        SaveBtn.setText("Salvar");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        CancelaBtn.setText("Cancelar");
        CancelaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaBtnActionPerformed(evt);
            }
        });

        ExcluirBtn.setText("Excluir");
        ExcluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBtnActionPerformed(evt);
            }
        });

        CPFTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        SalarioLbl.setText("Salário");

        FuncaoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionário", "Gerente" }));
        FuncaoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncaoComboActionPerformed(evt);
            }
        });

        FuncaoLbl.setText("Função");

        SalarioSpinner.setModel(new javax.swing.SpinnerNumberModel(800.0f, 800.0f, null, 0.01f));

        SenhaLbl.setText("Senha");

        SenhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormProdutoPanelLayout = new javax.swing.GroupLayout(FormProdutoPanel);
        FormProdutoPanel.setLayout(FormProdutoPanelLayout);
        FormProdutoPanelLayout.setHorizontalGroup(
            FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                        .addComponent(FuncionarioTxt)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                        .addComponent(NomeLbl)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                        .addComponent(CPFLbl)
                        .addGap(161, 161, 161))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FuncaoLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SenhaLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(151, 151, 151))
            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addComponent(SenhaField)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SalarioLbl)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                        .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SalarioSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeparatorFuncionarioForm)
                            .addComponent(CPFTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FormProdutoPanelLayout.createSequentialGroup()
                                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CancelaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addComponent(SaveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addComponent(FuncaoCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        FormProdutoPanelLayout.setVerticalGroup(
            FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                .addComponent(FuncionarioTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparatorFuncionarioForm, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeLbl)
                .addGap(4, 4, 4)
                .addComponent(NomeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(CPFLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CPFTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(SalarioLbl)
                .addGap(4, 4, 4)
                .addComponent(SalarioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FuncaoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FuncaoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SenhaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SenhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormProdutoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FormProdutoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaBtnActionPerformed
        dispose();
    }//GEN-LAST:event_CancelaBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        
        Funcionario f;
        f = new Funcionario( Long.parseLong(CPFTxtField.getText()), NomeTxtField.getText(), (Float) SalarioSpinner.getValue() , String.valueOf(SenhaField.getPassword()), (int) FuncaoCombo.getSelectedIndex());

        
        if(flag >= 1){//se a flag for 1  remove o funcionario antes de reinseri-lo com os dados adequados
            for(int i = 0; i < this.funcionarios.size(); i++){
                if(funcionarios.get(i).getNome().toUpperCase().equals(oldName.toUpperCase())){ //se houver funcionario com nome igual
                    funcionarios.remove(i);
                 }    
            }
        } 
        this.funcionarios.add(f);
        this.funcionarioTM.refresh();
        dispose();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ExcluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBtnActionPerformed
        
        if(JOptionPane.showConfirmDialog(null, "Tem que deseja excluir este funcionario?") == 0){ //se clicar em confirmar
            for(int i = 0; i < this.funcionarios.size(); i++){
                if(funcionarios.get(i).getNome().toUpperCase().equals(oldName.toUpperCase())){ //se houver funcionario com nome igual
                    funcionarios.remove(i);
                 }    
            }
            this.funcionarioTM.refresh();
            this.dispose();
        }
        
    }//GEN-LAST:event_ExcluirBtnActionPerformed

    private void CategoriaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaComboActionPerformed

    private void FuncaoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncaoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuncaoComboActionPerformed

    private void SenhaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFLbl;
    private javax.swing.JTextField CPFTxtField;
    private javax.swing.JButton CancelaBtn;
    private javax.swing.JComboBox<String> CategoriaCombo;
    private javax.swing.JButton ExcluirBtn;
    private javax.swing.JPanel FormProdutoPanel;
    private javax.swing.JComboBox<String> FuncaoCombo;
    private javax.swing.JLabel FuncaoLbl;
    private javax.swing.JLabel FuncionarioTxt;
    private javax.swing.JLabel NomeLbl;
    private javax.swing.JTextField NomeTxtField;
    private javax.swing.JLabel SalarioLbl;
    private javax.swing.JSpinner SalarioSpinner;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JPasswordField SenhaField;
    private javax.swing.JLabel SenhaLbl;
    private javax.swing.JSeparator SeparatorFuncionarioForm;
    // End of variables declaration//GEN-END:variables
}
