/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabacaria.views;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tabacaria.models.Categoria;
import tabacaria.models.CategoriaTableModel;


/**
 *
 * @author pedro
 */
public class FormularioCategoria extends javax.swing.JFrame {

    private Categoria categoria;
    ArrayList<Categoria> categorias;
    CategoriaTableModel categoriaTM;
    private int flag;
    private String oldName;
    public FormularioCategoria() {
        initComponents();
    }

    FormularioCategoria(Categoria c, ArrayList<Categoria> categorias, CategoriaTableModel ctm, int flag) { //flag diz se é pra adicionar ou atualizar
        this.categoria = c;
        this.categorias = categorias;
        this.categoriaTM = ctm;
        this.flag = flag;
        this.setDefaultCloseOperation( JFrame.HIDE_ON_CLOSE );
        this.setSize(360, 400);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.oldName = c.getNome();
        
        initComponents();
        
        if(flag == 1){ //se for para alterar
            NomeTxtField.setText(c.getNome());
            DescricaoTxtArea.setText(String.valueOf(c.getDescricao()));
            TaxaSpinner.setValue(c.getTaxa());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoriaCombo = new javax.swing.JComboBox<>();
        FormProdutoPanel = new javax.swing.JPanel();
        NomeTxtField = new javax.swing.JTextField();
        NomeLbl = new javax.swing.JLabel();
        CategoriaTxt = new javax.swing.JLabel();
        DescricaoLbl = new javax.swing.JLabel();
        SeparatorFormCategoria = new javax.swing.JSeparator();
        SaveBtn = new javax.swing.JButton();
        CancelaBtn = new javax.swing.JButton();
        ExcluirBtn = new javax.swing.JButton();
        TaxaLbl = new javax.swing.JLabel();
        DescricaoScrollPane = new javax.swing.JScrollPane();
        DescricaoTxtArea = new javax.swing.JTextArea();
        TaxaSpinner = new javax.swing.JSpinner();

        CategoriaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria Teste" }));
        CategoriaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaComboActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(354, 274));

        FormProdutoPanel.setBackground(new java.awt.Color(255, 255, 255));
        FormProdutoPanel.setMinimumSize(new java.awt.Dimension(354, 274));
        FormProdutoPanel.setPreferredSize(new java.awt.Dimension(354, 274));

        NomeTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        NomeLbl.setText("Nome");

        CategoriaTxt.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        CategoriaTxt.setForeground(new java.awt.Color(255, 204, 51));
        CategoriaTxt.setText("Categoria");

        DescricaoLbl.setText("Descrição");

        SeparatorFormCategoria.setForeground(new java.awt.Color(255, 204, 0));

        SaveBtn.setText("Salvar");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        CancelaBtn.setText("Cancelar");
        CancelaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaBtnActionPerformed(evt);
            }
        });

        ExcluirBtn.setText("Excluir");
        ExcluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBtnActionPerformed(evt);
            }
        });

        TaxaLbl.setText("Taxa de Impostos");

        DescricaoTxtArea.setColumns(20);
        DescricaoTxtArea.setRows(5);
        DescricaoScrollPane.setViewportView(DescricaoTxtArea);

        TaxaSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));

        javax.swing.GroupLayout FormProdutoPanelLayout = new javax.swing.GroupLayout(FormProdutoPanel);
        FormProdutoPanel.setLayout(FormProdutoPanelLayout);
        FormProdutoPanelLayout.setHorizontalGroup(
            FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeTxtField)
                            .addComponent(SeparatorFormCategoria, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                                .addComponent(DescricaoLbl)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FormProdutoPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(NomeLbl)))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                        .addComponent(CancelaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DescricaoScrollPane))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProdutoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CategoriaTxt)
                .addGap(123, 123, 123))
            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(TaxaLbl))
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(TaxaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FormProdutoPanelLayout.setVerticalGroup(
            FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                .addComponent(CategoriaTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparatorFormCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeLbl)
                .addGap(4, 4, 4)
                .addComponent(NomeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescricaoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescricaoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TaxaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TaxaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormProdutoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormProdutoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaBtnActionPerformed
        dispose();
    }//GEN-LAST:event_CancelaBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        
        Categoria c;
        c = new Categoria(NomeTxtField.getText(), DescricaoTxtArea.getText(),(Float) TaxaSpinner.getValue());

        
        if(flag == 1){//se a flag for 1  remove o categoria antes de reinseri-lo com os dados adequados
            for(int i = 0; i < this.categorias.size(); i++){
                if(categorias.get(i).getNome().toUpperCase().equals(oldName.toUpperCase())){ //se houver categoria com nome igual
                    categorias.remove(i);
                 }    
            }
        } 
        this.categorias.add(c);
        this.categoriaTM.refresh();
        dispose();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ExcluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBtnActionPerformed
        
        if(JOptionPane.showConfirmDialog(null, "Tem que deseja excluir esta categoria?") == 0){ //se clicar em confirmar
            for(int i = 0; i < this.categorias.size(); i++){
                if(categorias.get(i).getNome().toUpperCase().equals(oldName.toUpperCase())){ //se houver categoria com nome igual
                    categorias.remove(i);
                 }    
            }
            this.categoriaTM.refresh();
            this.dispose();
        }
        
    }//GEN-LAST:event_ExcluirBtnActionPerformed

    private void CategoriaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelaBtn;
    private javax.swing.JComboBox<String> CategoriaCombo;
    private javax.swing.JLabel CategoriaTxt;
    private javax.swing.JLabel DescricaoLbl;
    private javax.swing.JScrollPane DescricaoScrollPane;
    private javax.swing.JTextArea DescricaoTxtArea;
    private javax.swing.JButton ExcluirBtn;
    private javax.swing.JPanel FormProdutoPanel;
    private javax.swing.JLabel NomeLbl;
    private javax.swing.JTextField NomeTxtField;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JSeparator SeparatorFormCategoria;
    private javax.swing.JLabel TaxaLbl;
    private javax.swing.JSpinner TaxaSpinner;
    // End of variables declaration//GEN-END:variables
}
