/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabacaria.views;

import tabacaria.models.CompraTableModel;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import tabacaria.models.Caixa;
import tabacaria.models.CaixaTableModel;
import tabacaria.models.Categoria;
import tabacaria.models.Cliente;
import tabacaria.models.Compra;
import tabacaria.models.Data;
import tabacaria.models.Estoque;
import tabacaria.models.EstoqueTableModel;
import tabacaria.models.Fornecedor;
import tabacaria.models.Item;


/**
 *
 * @author pedro
 */
public class FormularioCompra extends javax.swing.JFrame {

    private Estoque estoque;
    private EstoqueTableModel estoqueTM;
    private TableRowSorter<EstoqueTableModel> sorterEstoque;
    private Compra compra;
    private CompraTableModel compraTM;
    private String[] nomesFornecedores;
    private DefaultComboBoxModel fornecedoresModel;
    private Compra oldCompra;
    private Caixa caixa;
    private ArrayList<Fornecedor> fornecedores;
    private CaixaTableModel caixaTM;
    private JLabel saldo;
    private ArrayList<Categoria> categorias;

    /**
     * Creates new form FormularioCompras
     */
    public FormularioCompra() {
        initComponents();
    }
    
    public FormularioCompra( Estoque estoque, EstoqueTableModel estoqueTM, Compra c, CompraTableModel compraTM, ArrayList<Fornecedor> fornecedores
            , Caixa caixa, CaixaTableModel caixaTM, javax.swing.JLabel SaldoLbl, ArrayList<Categoria> categorias, int flag) 
                throws CloneNotSupportedException{
        this.estoque = estoque ;
        this.estoqueTM = estoqueTM;
        this.sorterEstoque = new TableRowSorter<>(estoqueTM);
        
        this.oldCompra = (Compra) c.clone();
        this.compra = c;
        
        this.compraTM = compraTM;
        
        this.nomesFornecedores = new String[fornecedores.size()];
        
        this.categorias = categorias;
        
        
        for(int i = 0; i<fornecedores.size(); i++){
            nomesFornecedores[i] = fornecedores.get(i).getNome();
        }
        
        this.fornecedoresModel = new DefaultComboBoxModel(nomesFornecedores);
        this.caixa = caixa;
        this.caixaTM = caixaTM;
        
        this.fornecedores = fornecedores;
        this.saldo = SaldoLbl;
        
        initComponents();
        
        if(flag == 1){
            for (int i =0; i < nomesFornecedores.length; i++){
                if(nomesFornecedores[i].equals(compra.getFornecedor().getNome()))
                    FornecedorCombo.setSelectedIndex(i);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OVPanel = new javax.swing.JPanel();
        CatalogoPanel = new javax.swing.JPanel();
        CatalogoScrollPane = new javax.swing.JScrollPane();
        CatalogoJTable = new javax.swing.JTable();
        CatalogoLabel = new javax.swing.JLabel();
        ProdutoSearchTxtField = new javax.swing.JTextField();
        filtertxt = new javax.swing.JLabel();
        addtxt = new javax.swing.JLabel();
        NovoProdutoBtn = new javax.swing.JButton();
        SeparatorOrdensCompra = new javax.swing.JSeparator();
        OrdensCompraLbl = new javax.swing.JLabel();
        PedidoPanel = new javax.swing.JPanel();
        PedidoScrollPane3 = new javax.swing.JScrollPane();
        PedidoJTable3 = new javax.swing.JTable();
        PedidoLbl = new javax.swing.JLabel();
        removealteratxt = new javax.swing.JLabel();
        FornecedorCombo = new javax.swing.JComboBox<>();
        FornecedorLabel = new javax.swing.JLabel();
        TransferImg = new javax.swing.JLabel();
        FinalizaOCBtn = new javax.swing.JButton();
        CancelaOCBtn = new javax.swing.JButton();
        voltarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        OVPanel.setBackground(new java.awt.Color(255, 255, 255));

        CatalogoPanel.setBackground(new java.awt.Color(255, 255, 255));
        CatalogoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 1, true));

        CatalogoJTable.setAutoCreateRowSorter(true);
        CatalogoJTable.setModel(estoqueTM);
        CatalogoJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatalogoJTableMouseClicked(evt);
            }
        });
        CatalogoScrollPane.setViewportView(CatalogoJTable);

        CatalogoLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CatalogoLabel.setText("Catálogo");

        ProdutoSearchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoSearchTxtFieldActionPerformed(evt);
            }
        });
        ProdutoSearchTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ProdutoSearchTxtFieldrefreshFilterProduto(evt);
            }
        });

        filtertxt.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        filtertxt.setText("(Filtre os produtos através do campo acima)");

        addtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addtxt.setText("Clique duas vezes em um produto para adicioná-lo à ordem de venda");

        NovoProdutoBtn.setBackground(new java.awt.Color(255, 255, 255));
        NovoProdutoBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NovoProdutoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/add.png"))); // NOI18N
        NovoProdutoBtn.setText("Novo Produto");
        NovoProdutoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoProdutoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CatalogoPanelLayout = new javax.swing.GroupLayout(CatalogoPanel);
        CatalogoPanel.setLayout(CatalogoPanelLayout);
        CatalogoPanelLayout.setHorizontalGroup(
            CatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatalogoPanelLayout.createSequentialGroup()
                .addGroup(CatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CatalogoPanelLayout.createSequentialGroup()
                        .addGroup(CatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CatalogoPanelLayout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(filtertxt))
                            .addGroup(CatalogoPanelLayout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(CatalogoLabel))
                            .addGroup(CatalogoPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(CatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CatalogoPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(NovoProdutoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addtxt))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CatalogoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CatalogoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                            .addComponent(ProdutoSearchTxtField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        CatalogoPanelLayout.setVerticalGroup(
            CatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatalogoPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(CatalogoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProdutoSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtertxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(CatalogoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NovoProdutoBtn)
                .addGap(22, 22, 22))
        );

        SeparatorOrdensCompra.setForeground(new java.awt.Color(255, 204, 0));

        OrdensCompraLbl.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 48)); // NOI18N
        OrdensCompraLbl.setForeground(new java.awt.Color(255, 204, 51));
        OrdensCompraLbl.setText("Ordem de Compra");

        PedidoPanel.setBackground(new java.awt.Color(255, 255, 255));
        PedidoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 1, true));

        PedidoJTable3.setAutoCreateRowSorter(true);
        PedidoJTable3.setModel(compraTM);
        PedidoJTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidoJTable3MouseClicked(evt);
            }
        });
        PedidoScrollPane3.setViewportView(PedidoJTable3);

        PedidoLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PedidoLbl.setText("Pedido");

        removealteratxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removealteratxt.setText("Clique duas vezes em um produto para removê-lo ou alterar a quandidade desejada");

        FornecedorCombo.setModel(fornecedoresModel);

        FornecedorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        FornecedorLabel.setText("Fornecedor:");

        javax.swing.GroupLayout PedidoPanelLayout = new javax.swing.GroupLayout(PedidoPanel);
        PedidoPanel.setLayout(PedidoPanelLayout);
        PedidoPanelLayout.setHorizontalGroup(
            PedidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PedidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedidoPanelLayout.createSequentialGroup()
                        .addGroup(PedidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PedidoScrollPane3)
                            .addComponent(FornecedorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidoPanelLayout.createSequentialGroup()
                                .addGap(0, 17, Short.MAX_VALUE)
                                .addComponent(removealteratxt)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PedidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FornecedorLabel)
                            .addComponent(PedidoLbl))
                        .addGap(225, 225, 225))))
        );
        PedidoPanelLayout.setVerticalGroup(
            PedidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(PedidoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FornecedorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FornecedorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PedidoScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removealteratxt)
                .addContainerGap())
        );

        TransferImg.setForeground(new java.awt.Color(255, 153, 51));
        TransferImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/horizontal (1).png"))); // NOI18N

        FinalizaOCBtn.setBackground(new java.awt.Color(255, 255, 255));
        FinalizaOCBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FinalizaOCBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/carrinho.png"))); // NOI18N
        FinalizaOCBtn.setText(" Finalizar Ordem de Venda");
        FinalizaOCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizaOCBtnActionPerformed(evt);
            }
        });

        CancelaOCBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelaOCBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CancelaOCBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/erro.png"))); // NOI18N
        CancelaOCBtn.setText(" Cancelar Ordem de Compra");
        CancelaOCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaOCBtnActionPerformed(evt);
            }
        });

        voltarBtn.setText("Voltar");

        javax.swing.GroupLayout OVPanelLayout = new javax.swing.GroupLayout(OVPanel);
        OVPanel.setLayout(OVPanelLayout);
        OVPanelLayout.setHorizontalGroup(
            OVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OVPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeparatorOrdensCompra)
                    .addGroup(OVPanelLayout.createSequentialGroup()
                        .addComponent(CatalogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TransferImg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(PedidoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OVPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(CancelaOCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FinalizaOCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(OVPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269)
                .addComponent(OrdensCompraLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OVPanelLayout.setVerticalGroup(
            OVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OVPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrdensCompraLbl)
                    .addComponent(voltarBtn))
                .addGap(20, 20, 20)
                .addComponent(SeparatorOrdensCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(OVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OVPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(OVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CatalogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PedidoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(OVPanelLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(TransferImg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinalizaOCBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelaOCBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(OVPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OVPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CatalogoJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatalogoJTableMouseClicked

        if (2 == evt.getClickCount()) {

            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            adicionaAoPedido(row);
        }
    }//GEN-LAST:event_CatalogoJTableMouseClicked

    private void ProdutoSearchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoSearchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutoSearchTxtFieldActionPerformed

    private void ProdutoSearchTxtFieldrefreshFilterProduto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProdutoSearchTxtFieldrefreshFilterProduto

    }//GEN-LAST:event_ProdutoSearchTxtFieldrefreshFilterProduto

    private void PedidoJTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PedidoJTable3MouseClicked
        if (2 == evt.getClickCount()) {

            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            alteraProdutoPedido(row);
        }
    }//GEN-LAST:event_PedidoJTable3MouseClicked

    private void FinalizaOCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizaOCBtnActionPerformed
        
        Fornecedor f = fornecedores.get(FornecedorCombo.getSelectedIndex());
        compra.setFornecedor(f);
        Calendar cal = Calendar.getInstance();
        compra.setData(new Data(
                cal.get(Calendar.DAY_OF_MONTH)
                , Calendar.MONTH +1
                , Calendar.YEAR
                       
        ));
        
        for(int i =0; i< oldCompra.getLista().size(); i++){ // para cada item presente na antiga lista de compras
            estoque.vender(oldCompra.getLista().get(i).getProduto().getNome(), oldCompra.getLista().get(i).getQuantidade() ); //removo-o
       
        }
        
        caixa.cancelaMovimentacao(oldCompra);
        
        
        for(int i =0; i< compra.getLista().size(); i++){ // para cada item presente na nova lista de compras
            estoque.incluir(compra.getLista().get(i)); //incluo no estoque os produtos
        
        }
        
        
        caixa.gravaMovimentacao(compra);
        
        estoqueTM.refresh();
        caixaTM.refresh();
        saldo.setText("R$: "+Float.toString(caixa.getSaldo()));
        dispose();
        
        
        
    }//GEN-LAST:event_FinalizaOCBtnActionPerformed

    private void CancelaOCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaOCBtnActionPerformed
        
        
        if(JOptionPane.showConfirmDialog(null, "Tem que deseja cancelar esta Compra?") == 0){ //se clicar em confirmar
            for(int i =0; i< oldCompra.getLista().size(); i++){ // para cada item presente na antiga lista de compras
                estoque.incluir(oldCompra.getLista().get(i)); //incluo de volta ao estoque os produtos
        
            }
            caixa.cancelaMovimentacao(oldCompra); //remove a transação
            this.caixaTM.refresh();
            saldo.setText("R$: "+Float.toString(caixa.getSaldo()));
            this.dispose();
        }
        
        
        caixa.cancelaMovimentacao(oldCompra);
    }//GEN-LAST:event_CancelaOCBtnActionPerformed

    private void NovoProdutoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoProdutoBtnActionPerformed
        Item i = new Item();
        
        FormularioProduto fp = new FormularioProduto(i, estoque, estoqueTM, categorias,  0); //flag 0 é adicionar
        
        
        
    
    }//GEN-LAST:event_NovoProdutoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelaOCBtn;
    private javax.swing.JTable CatalogoJTable;
    private javax.swing.JLabel CatalogoLabel;
    private javax.swing.JPanel CatalogoPanel;
    private javax.swing.JScrollPane CatalogoScrollPane;
    private javax.swing.JButton FinalizaOCBtn;
    private javax.swing.JComboBox<String> FornecedorCombo;
    private javax.swing.JLabel FornecedorLabel;
    private javax.swing.JButton NovoProdutoBtn;
    private javax.swing.JPanel OVPanel;
    private javax.swing.JLabel OrdensCompraLbl;
    private javax.swing.JTable PedidoJTable3;
    private javax.swing.JLabel PedidoLbl;
    private javax.swing.JPanel PedidoPanel;
    private javax.swing.JScrollPane PedidoScrollPane3;
    private javax.swing.JTextField ProdutoSearchTxtField;
    private javax.swing.JSeparator SeparatorOrdensCompra;
    private javax.swing.JLabel TransferImg;
    private javax.swing.JLabel addtxt;
    private javax.swing.JLabel filtertxt;
    private javax.swing.JLabel removealteratxt;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables

    private void adicionaAoPedido(int row) {
        
        AlteracaoQuantidadeCompra aqc = new AlteracaoQuantidadeCompra(estoque.getItem(row), compra, compraTM, 0);
        
        
    }

    private void alteraProdutoPedido(int row) {
        AlteracaoQuantidadeCompra aqc = new AlteracaoQuantidadeCompra(compra.getLista().get(row), compra, compraTM, 1);
    }
}
