/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabacaria.views;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tabacaria.models.Cliente;
import tabacaria.models.ClienteTableModel;
import tabacaria.models.Data;
import tabacaria.models.Estoque;
import tabacaria.models.EstoqueTableModel;
import tabacaria.models.Item;
import tabacaria.models.Produto;

/**
 *
 * @author pedro
 */
public class FormularioCliente extends javax.swing.JFrame {

    private Cliente cliente;
    ArrayList<Cliente> clientes;
    ClienteTableModel clienteTM;
    private int flag;
    private String oldName;
    public FormularioCliente() {
        initComponents();
    }

    FormularioCliente(Cliente c, ArrayList<Cliente> clientes, ClienteTableModel ctm, int flag) { //flag diz se é pra adicionar ou atualizar
        this.cliente = c;
        this.clientes = clientes;
        this.clienteTM = ctm;
        this.flag = flag;
        this.setDefaultCloseOperation( JFrame.HIDE_ON_CLOSE );
        this.setSize(360, 295);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.oldName = c.getNome();
        
        initComponents();
        
        if(flag == 1){ //se for para alterar
            NomeTxtField.setText(c.getNome());
            CPFTxtField.setText(String.valueOf(c.getCPF()));
            DiaCbox.setSelectedItem(c.getNascimento().getDia());
            MesCbox.setSelectedIndex(c.getNascimento().getMes()-1);
            AnoCbox.setSelectedItem(c.getNascimento().getAno());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoriaCombo = new javax.swing.JComboBox<>();
        FormProdutoPanel = new javax.swing.JPanel();
        NomeTxtField = new javax.swing.JTextField();
        NomeLbl = new javax.swing.JLabel();
        ProdutoTxt = new javax.swing.JLabel();
        CategoriaLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SaveBtn = new javax.swing.JButton();
        CancelaBtn = new javax.swing.JButton();
        ExcluirBtn = new javax.swing.JButton();
        CPFTxtField = new javax.swing.JTextField();
        NascientoLbl1 = new javax.swing.JLabel();
        DiaCbox = new javax.swing.JComboBox<>();
        MesCbox = new javax.swing.JComboBox<>();
        AnoCbox = new javax.swing.JComboBox<>();

        CategoriaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria Teste" }));
        CategoriaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaComboActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(354, 274));

        FormProdutoPanel.setBackground(new java.awt.Color(255, 255, 255));
        FormProdutoPanel.setMinimumSize(new java.awt.Dimension(354, 274));
        FormProdutoPanel.setPreferredSize(new java.awt.Dimension(354, 274));

        NomeTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        NomeLbl.setText("Nome");

        ProdutoTxt.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        ProdutoTxt.setForeground(new java.awt.Color(255, 204, 51));
        ProdutoTxt.setText("Cliente");

        CategoriaLbl.setText("CPF");

        jSeparator1.setForeground(new java.awt.Color(255, 204, 0));

        SaveBtn.setText("Salvar");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        CancelaBtn.setText("Cancelar");
        CancelaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaBtnActionPerformed(evt);
            }
        });

        ExcluirBtn.setText("Excluir");
        ExcluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBtnActionPerformed(evt);
            }
        });

        CPFTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        NascientoLbl1.setText("Data de Nasciento");

        DiaCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DiaCbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaCboxActionPerformed(evt);
            }
        });

        MesCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        MesCbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesCboxActionPerformed(evt);
            }
        });

        AnoCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", " " }));
        AnoCbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoCboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormProdutoPanelLayout = new javax.swing.GroupLayout(FormProdutoPanel);
        FormProdutoPanel.setLayout(FormProdutoPanelLayout);
        FormProdutoPanelLayout.setHorizontalGroup(
            FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeTxtField)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CPFTxtField)))
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(CancelaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(CategoriaLbl)
                                    .addComponent(NomeLbl)
                                    .addComponent(ProdutoTxt)))
                            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                        .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NascientoLbl1)
                                    .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                                        .addComponent(MesCbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(9, 9, 9))))
                            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DiaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AnoCbox, 0, 94, Short.MAX_VALUE))))
                .addContainerGap())
        );
        FormProdutoPanelLayout.setVerticalGroup(
            FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProdutoPanelLayout.createSequentialGroup()
                .addComponent(ProdutoTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeLbl)
                .addGap(4, 4, 4)
                .addComponent(NomeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CategoriaLbl)
                .addGap(10, 10, 10)
                .addComponent(CPFTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NascientoLbl1)
                .addGap(4, 4, 4)
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnoCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormProdutoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FormProdutoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaBtnActionPerformed
        dispose();
    }//GEN-LAST:event_CancelaBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        
        Cliente c;
        c = new Cliente(NomeTxtField.getText(),Long.parseLong(CPFTxtField.getText()), 
                new Data(Integer.parseInt(DiaCbox.getSelectedItem().toString()) , (int) MesCbox.getSelectedIndex() +1, Integer.parseInt(AnoCbox.getSelectedItem().toString())) );

        
        if(flag == 1){//se a flag for 1  remove o cliente antes de reinseri-lo com os dados adequados
            for(int i = 0; i < this.clientes.size(); i++){
                if(clientes.get(i).getNome().toUpperCase().equals(oldName.toUpperCase())){ //se houver cliente com nome igual
                    clientes.remove(i);
                 }    
            }
        } 
        this.clientes.add(c);
        this.clienteTM.refresh();
        dispose();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ExcluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBtnActionPerformed
        
        if(JOptionPane.showConfirmDialog(null, "Tem que deseja excluir este cliente?") == 0){ //se clicar em confirmar
            for(int i = 0; i < this.clientes.size(); i++){
                if(clientes.get(i).getNome().toUpperCase().equals(oldName.toUpperCase())){ //se houver cliente com nome igual
                    clientes.remove(i);
                 }    
            }
            this.clienteTM.refresh();
            this.dispose();
        }
        
    }//GEN-LAST:event_ExcluirBtnActionPerformed

    private void CategoriaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaComboActionPerformed

    private void DiaCboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaCboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaCboxActionPerformed

    private void MesCboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesCboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MesCboxActionPerformed

    private void AnoCboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoCboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoCboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AnoCbox;
    private javax.swing.JTextField CPFTxtField;
    private javax.swing.JButton CancelaBtn;
    private javax.swing.JComboBox<String> CategoriaCombo;
    private javax.swing.JLabel CategoriaLbl;
    private javax.swing.JComboBox<String> DiaCbox;
    private javax.swing.JButton ExcluirBtn;
    private javax.swing.JPanel FormProdutoPanel;
    private javax.swing.JComboBox<String> MesCbox;
    private javax.swing.JLabel NascientoLbl1;
    private javax.swing.JLabel NomeLbl;
    private javax.swing.JTextField NomeTxtField;
    private javax.swing.JLabel ProdutoTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
