/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabacaria.views;

import helpers.Arquivo;
import java.io.IOException;
import tabacaria.models.VendaTableModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.RowFilter;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.TableRowSorter;
import tabacaria.models.Caixa;
import tabacaria.models.CaixaTableModel;
import tabacaria.models.Categoria;
import tabacaria.models.CategoriaTableModel;
import tabacaria.models.Cliente;
import tabacaria.models.ClienteTableModel;
import tabacaria.models.Compra;
import tabacaria.models.CompraTableModel;
import tabacaria.models.Estoque;
import tabacaria.models.EstoqueTableModel;
import tabacaria.models.Fornecedor;
import tabacaria.models.FornecedorTableModel;
import tabacaria.models.Funcionario;
import tabacaria.models.FuncionarioTableModel;
import tabacaria.models.Item;
import tabacaria.models.Transacao;
import tabacaria.models.Venda;

/**
 *
 * @author pedro
 */
public class Index extends javax.swing.JPanel {

    
    
    private Funcionario funcLogado;
    
    //Variaveis de estoque
    private final Estoque estoque;
    private final EstoqueTableModel estoqueTM;
    TableRowSorter<EstoqueTableModel> sorterEstoque;
    
    //variaveis de clientes
    private final  ArrayList<Cliente> clientes;
    private final ClienteTableModel clienteTM;
    TableRowSorter<ClienteTableModel> sorterClientes;
    
    
    //variaveis de categoria
    private final ArrayList<Categoria> categorias;
    private final CategoriaTableModel categoriaTM;
    private final TableRowSorter<CategoriaTableModel> sorterCategorias;
    
    //variaveis de fornecedor
    private final ArrayList<Fornecedor> fornecedores;
    private final FornecedorTableModel fornecedorTM;
    private final TableRowSorter<FornecedorTableModel> sorterFornecedores;
    
    //variaveis funcionarios
    private final ArrayList<Funcionario> funcionarios;
    private final FuncionarioTableModel funcionarioTM;
    private final TableRowSorter<FuncionarioTableModel> sorterFuncionario;
    
    //variaveis caixa (controle de transacoes)
    private final Caixa caixa;
    private final CaixaTableModel caixaTM;
    private final TableRowSorter<CaixaTableModel> sorterCaixa;
    
    public Index(Estoque estoque, ArrayList<Cliente> clientes, ArrayList<Categoria> categorias, ArrayList<Fornecedor> fornecedores, ArrayList<Funcionario> funcionarios, Caixa caixa) {
        this.estoque = estoque;
        this.estoqueTM = new EstoqueTableModel(estoque);
        this.sorterEstoque = new TableRowSorter<>(estoqueTM);
        
        this.clientes = clientes;
        this.clienteTM = new ClienteTableModel(clientes);
        this.sorterClientes = new TableRowSorter<>(clienteTM);
        
        this.categorias = categorias;
        this.categoriaTM = new CategoriaTableModel(categorias);
        this.sorterCategorias = new TableRowSorter<>(categoriaTM);
        
        this.fornecedores = fornecedores;
        this.fornecedorTM = new FornecedorTableModel(fornecedores);
        this.sorterFornecedores = new TableRowSorter<>(fornecedorTM);
        
        
        this.funcionarios = funcionarios;
        this.funcionarioTM = new FuncionarioTableModel(funcionarios);
        this.sorterFuncionario = new TableRowSorter<>(funcionarioTM);
        
        this.caixa = caixa;
        this.caixaTM = new CaixaTableModel(caixa);
        this.sorterCaixa = new TableRowSorter<>(caixaTM);
        
        
        
        initComponents();
        
        //Cria os sorters para a filtragem das tabelas após os componentes gráficos terem sido iniciados
        
        ProdutosJTable.setRowSorter(this.sorterEstoque);
        ClientesJTable.setRowSorter(this.sorterClientes);
        SaldoValue.setText("R$: "+Float.toString(this.caixa.getSaldo()));
        
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FundoLogo = new javax.swing.JPanel();
        LogoImg = new javax.swing.JLabel();
        TabacariaTxt = new javax.swing.JLabel();
        JanelaDeAbas = new javax.swing.JTabbedPane();
        JPEstoque = new javax.swing.JPanel();
        ProdutoLabel = new javax.swing.JLabel();
        ProdutoSearchTxtField = new javax.swing.JTextField();
        ProdutoSearchBtn = new javax.swing.JButton();
        ProdutosScrollPane = new javax.swing.JScrollPane();
        ProdutosJTable = new javax.swing.JTable();
        GerenciarCategoriaBtn = new javax.swing.JButton();
        JPClientes = new javax.swing.JPanel();
        ClienteLabel = new javax.swing.JLabel();
        ClientesScrollPane = new javax.swing.JScrollPane();
        ClientesJTable = new javax.swing.JTable();
        ClienteSearchTxtField = new javax.swing.JTextField();
        ClienteSearchBtn = new javax.swing.JButton();
        ClienteAddBtn = new javax.swing.JButton();
        Fornecedores = new javax.swing.JPanel();
        FornecedorLabel = new javax.swing.JLabel();
        FornecedorSearchTxtField = new javax.swing.JTextField();
        FornecedorSearchBtn = new javax.swing.JButton();
        FornecedorScrollPane = new javax.swing.JScrollPane();
        FornecedoresJTable = new javax.swing.JTable();
        FornecedorAddBtn = new javax.swing.JButton();
        JPFuncionarios = new javax.swing.JPanel();
        FuncionarioLabel = new javax.swing.JLabel();
        FuncionarioSearchTxtField = new javax.swing.JTextField();
        FuncionarioSearchBtn = new javax.swing.JButton();
        FuncionariosScrollPane = new javax.swing.JScrollPane();
        FuncionariosJtable = new javax.swing.JTable();
        FuncionarioAddBtn = new javax.swing.JButton();
        JPRelatorios = new javax.swing.JPanel();
        RelatoriosScrollPane = new javax.swing.JScrollPane();
        RelatoriosJtable = new javax.swing.JTable();
        SaldoLbl = new javax.swing.JLabel();
        SaldoValue = new javax.swing.JLabel();
        RCompraBtn = new javax.swing.JButton();
        EVendaBtn = new javax.swing.JButton();
        ConfigBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        FundoLogo.setBackground(new java.awt.Color(255, 255, 255));

        LogoImg.setBackground(new java.awt.Color(255, 255, 255));
        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/free_horizontal_on_white_by_logaster.png"))); // NOI18N

        TabacariaTxt.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 82)); // NOI18N
        TabacariaTxt.setForeground(new java.awt.Color(255, 204, 51));
        TabacariaTxt.setText("Tabacaria");

        javax.swing.GroupLayout FundoLogoLayout = new javax.swing.GroupLayout(FundoLogo);
        FundoLogo.setLayout(FundoLogoLayout);
        FundoLogoLayout.setHorizontalGroup(
            FundoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoImg)
                .addGap(42, 42, 42)
                .addComponent(TabacariaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(181, 181, 181))
        );
        FundoLogoLayout.setVerticalGroup(
            FundoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoLogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(FundoLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabacariaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JanelaDeAbas.setBackground(new java.awt.Color(255, 255, 255));
        JanelaDeAbas.setForeground(new java.awt.Color(255, 153, 0));
        JanelaDeAbas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JPEstoque.setBackground(new java.awt.Color(255, 255, 255));

        ProdutoLabel.setText("Produto:");

        ProdutoSearchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoSearchTxtFieldActionPerformed(evt);
            }
        });
        ProdutoSearchTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                refreshFilterProduto(evt);
            }
        });

        ProdutoSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/search.png"))); // NOI18N
        ProdutoSearchBtn.setText("Buscar");
        ProdutoSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoSearchBtnActionPerformed(evt);
            }
        });

        ProdutosJTable.setAutoCreateRowSorter(true);
        ProdutosJTable.setModel(estoqueTM);
        ProdutosJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdutosJTableMouseClicked(evt);
            }
        });
        ProdutosScrollPane.setViewportView(ProdutosJTable);

        GerenciarCategoriaBtn.setBackground(new java.awt.Color(255, 255, 255));
        GerenciarCategoriaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/settings.png"))); // NOI18N
        GerenciarCategoriaBtn.setText("Gerenciar Categorias");
        GerenciarCategoriaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarCategoriaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPEstoqueLayout = new javax.swing.GroupLayout(JPEstoque);
        JPEstoque.setLayout(JPEstoqueLayout);
        JPEstoqueLayout.setHorizontalGroup(
            JPEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProdutosScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPEstoqueLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ProdutoSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPEstoqueLayout.createSequentialGroup()
                        .addGroup(JPEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GerenciarCategoriaBtn)
                            .addGroup(JPEstoqueLayout.createSequentialGroup()
                                .addComponent(ProdutoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProdutoSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 187, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPEstoqueLayout.setVerticalGroup(
            JPEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProdutoLabel)
                    .addComponent(ProdutoSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProdutoSearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProdutosScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GerenciarCategoriaBtn)
                .addGap(7, 7, 7))
        );

        JanelaDeAbas.addTab("Estoque", JPEstoque);

        JPClientes.setBackground(new java.awt.Color(255, 255, 255));

        ClienteLabel.setText("Cliente:");

        ClientesJTable.setModel(clienteTM);
        ClientesJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientesJTableMouseClicked(evt);
            }
        });
        ClientesScrollPane.setViewportView(ClientesJTable);

        ClienteSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/search.png"))); // NOI18N
        ClienteSearchBtn.setText("Buscar");
        ClienteSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteSearchBtnActionPerformed(evt);
            }
        });

        ClienteAddBtn.setBackground(new java.awt.Color(255, 255, 255));
        ClienteAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/add.png"))); // NOI18N
        ClienteAddBtn.setText("Novo Cliente");
        ClienteAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteAddBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPClientesLayout = new javax.swing.GroupLayout(JPClientes);
        JPClientes.setLayout(JPClientesLayout);
        JPClientesLayout.setHorizontalGroup(
            JPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClientesScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addGroup(JPClientesLayout.createSequentialGroup()
                        .addComponent(ClienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClienteSearchTxtField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClienteSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ClienteAddBtn)))
                .addContainerGap())
        );
        JPClientesLayout.setVerticalGroup(
            JPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteLabel)
                    .addComponent(ClienteSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClienteSearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClientesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClienteAddBtn)
                .addContainerGap())
        );

        JanelaDeAbas.addTab("Clientes", JPClientes);

        Fornecedores.setBackground(new java.awt.Color(255, 255, 255));

        FornecedorLabel.setText("Fornecedor:");

        FornecedorSearchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FornecedorSearchTxtFieldActionPerformed(evt);
            }
        });
        FornecedorSearchTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FornecedorSearchTxtFieldrefreshFilterProduto(evt);
            }
        });

        FornecedorSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/search.png"))); // NOI18N
        FornecedorSearchBtn.setText("Buscar");
        FornecedorSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FornecedorSearchBtnActionPerformed(evt);
            }
        });

        FornecedoresJTable.setAutoCreateRowSorter(true);
        FornecedoresJTable.setModel(fornecedorTM);
        FornecedoresJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FornecedoresJTableMouseClicked(evt);
            }
        });
        FornecedorScrollPane.setViewportView(FornecedoresJTable);

        FornecedorAddBtn.setBackground(new java.awt.Color(255, 255, 255));
        FornecedorAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/add.png"))); // NOI18N
        FornecedorAddBtn.setText("Novo Fornecedor");
        FornecedorAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FornecedorAddBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FornecedoresLayout = new javax.swing.GroupLayout(Fornecedores);
        Fornecedores.setLayout(FornecedoresLayout);
        FornecedoresLayout.setHorizontalGroup(
            FornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FornecedorScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addGroup(FornecedoresLayout.createSequentialGroup()
                        .addComponent(FornecedorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FornecedorSearchTxtField)
                        .addGap(12, 12, 12)
                        .addComponent(FornecedorSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FornecedoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FornecedorAddBtn)))
                .addContainerGap())
        );
        FornecedoresLayout.setVerticalGroup(
            FornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FornecedorLabel)
                    .addComponent(FornecedorSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FornecedorSearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FornecedorScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FornecedorAddBtn)
                .addContainerGap())
        );

        JanelaDeAbas.addTab("Fornecedores", Fornecedores);

        JPFuncionarios.setBackground(new java.awt.Color(255, 255, 255));

        FuncionarioLabel.setText("Funcionário:");

        FuncionarioSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/search.png"))); // NOI18N
        FuncionarioSearchBtn.setText("Buscar");
        FuncionarioSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioSearchBtnActionPerformed(evt);
            }
        });

        FuncionariosJtable.setModel(funcionarioTM);
        FuncionariosJtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FuncionariosJtableMouseClicked(evt);
            }
        });
        FuncionariosScrollPane.setViewportView(FuncionariosJtable);

        FuncionarioAddBtn.setBackground(new java.awt.Color(255, 255, 255));
        FuncionarioAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/add.png"))); // NOI18N
        FuncionarioAddBtn.setText("Novo Funcionário");
        FuncionarioAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioAddBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPFuncionariosLayout = new javax.swing.GroupLayout(JPFuncionarios);
        JPFuncionarios.setLayout(JPFuncionariosLayout);
        JPFuncionariosLayout.setHorizontalGroup(
            JPFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FuncionariosScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addGroup(JPFuncionariosLayout.createSequentialGroup()
                        .addComponent(FuncionarioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FuncionarioSearchTxtField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FuncionarioSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPFuncionariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FuncionarioAddBtn)))
                .addContainerGap())
        );
        JPFuncionariosLayout.setVerticalGroup(
            JPFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FuncionarioLabel)
                    .addComponent(FuncionarioSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FuncionarioSearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FuncionariosScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FuncionarioAddBtn)
                .addContainerGap())
        );

        JanelaDeAbas.addTab("Funcionários", JPFuncionarios);

        JPRelatorios.setBackground(new java.awt.Color(255, 255, 255));

        RelatoriosJtable.setModel(caixaTM);
        RelatoriosJtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RelatoriosJtableMouseClicked(evt);
            }
        });
        RelatoriosScrollPane.setViewportView(RelatoriosJtable);

        SaldoLbl.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        SaldoLbl.setText("Saldo:");

        SaldoValue.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        SaldoValue.setForeground(new java.awt.Color(0, 51, 255));
        SaldoValue.setText("R$ 2222,22");

        javax.swing.GroupLayout JPRelatoriosLayout = new javax.swing.GroupLayout(JPRelatorios);
        JPRelatorios.setLayout(JPRelatoriosLayout);
        JPRelatoriosLayout.setHorizontalGroup(
            JPRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RelatoriosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(JPRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaldoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaldoLbl))
                .addContainerGap())
        );
        JPRelatoriosLayout.setVerticalGroup(
            JPRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPRelatoriosLayout.createSequentialGroup()
                        .addComponent(SaldoLbl)
                        .addGap(3, 3, 3)
                        .addComponent(SaldoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(RelatoriosScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap())
        );

        JanelaDeAbas.addTab("Fluxo de Caixa", JPRelatorios);

        RCompraBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RCompraBtn.setForeground(new java.awt.Color(255, 153, 0));
        RCompraBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/delivery-truck.png"))); // NOI18N
        RCompraBtn.setText("Receber Carregamento");
        RCompraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCompraBtnActionPerformed(evt);
            }
        });

        EVendaBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EVendaBtn.setForeground(new java.awt.Color(255, 153, 0));
        EVendaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/cart.png"))); // NOI18N
        EVendaBtn.setText("Efetuar Venda");
        EVendaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVendaBtnActionPerformed(evt);
            }
        });

        ConfigBtn.setBackground(new java.awt.Color(255, 255, 255));
        ConfigBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabacaria/img/settings.png"))); // NOI18N
        ConfigBtn.setText("Configurações");
        ConfigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FundoLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JanelaDeAbas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RCompraBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfigBtn)
                        .addGap(103, 103, 103)
                        .addComponent(EVendaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FundoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JanelaDeAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RCompraBtn)
                    .addComponent(EVendaBtn)
                    .addComponent(ConfigBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProdutoSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutoSearchBtnActionPerformed

    private void ClienteSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteSearchBtnActionPerformed

    private void FuncionarioSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuncionarioSearchBtnActionPerformed

    private void ProdutoSearchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoSearchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutoSearchTxtFieldActionPerformed

    private void refreshFilterProduto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_refreshFilterProduto
        RowFilter<EstoqueTableModel, Object> rf = null;
        //If current expression doesn't parse, don't update.
        try {
            rf = RowFilter.regexFilter("(?i)" + ProdutoSearchTxtField.getText(),0);
        } catch (java.util.regex.PatternSyntaxException e) {
            return;
        }
        sorterEstoque.setRowFilter(rf);
    }//GEN-LAST:event_refreshFilterProduto

    private void RCompraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCompraBtnActionPerformed
        try {
            novaOrdemCompra();
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RCompraBtnActionPerformed

    private void ProdutosJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdutosJTableMouseClicked
        
        if (2 == evt.getClickCount()) {
        
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            alterarProduto(row);
        }
    }//GEN-LAST:event_ProdutosJTableMouseClicked

    private void ClienteAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteAddBtnActionPerformed
        addCliente();
    }//GEN-LAST:event_ClienteAddBtnActionPerformed

    private void ClientesJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesJTableMouseClicked
        if (2 == evt.getClickCount()) {
        
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            alterarCliente(row);
        }
    }//GEN-LAST:event_ClientesJTableMouseClicked

    private void GerenciarCategoriaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarCategoriaBtnActionPerformed
        controleCategorias();
    }//GEN-LAST:event_GerenciarCategoriaBtnActionPerformed

    private void FornecedorSearchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FornecedorSearchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FornecedorSearchTxtFieldActionPerformed

    private void FornecedorSearchTxtFieldrefreshFilterProduto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FornecedorSearchTxtFieldrefreshFilterProduto
        // TODO add your handling code here:
    }//GEN-LAST:event_FornecedorSearchTxtFieldrefreshFilterProduto

    private void FornecedorSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FornecedorSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FornecedorSearchBtnActionPerformed

    private void FornecedoresJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FornecedoresJTableMouseClicked
        if (2 == evt.getClickCount()) {
        
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            alterarFornecedor(row);
        }
    }//GEN-LAST:event_FornecedoresJTableMouseClicked

    private void FornecedorAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FornecedorAddBtnActionPerformed
        addFornecedor();
    }//GEN-LAST:event_FornecedorAddBtnActionPerformed

    private void FuncionarioAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioAddBtnActionPerformed
        addFuncionario();
    }//GEN-LAST:event_FuncionarioAddBtnActionPerformed

    private void FuncionariosJtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FuncionariosJtableMouseClicked
        if (2 == evt.getClickCount()) {
        
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            alterarFuncionario(row);
        }
    }//GEN-LAST:event_FuncionariosJtableMouseClicked

    private void EVendaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVendaBtnActionPerformed
        try {
            novaOrdemVenda();
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EVendaBtnActionPerformed

    private void RelatoriosJtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatoriosJtableMouseClicked
        if (2 == evt.getClickCount()) {
        
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            try {
                alterarTransacao(row);
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_RelatoriosJtableMouseClicked

    private void ConfigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigBtnActionPerformed
        Configuracoes config = new Configuracoes(  estoque,  clientes, categorias,  fornecedores,  funcionarios, caixa
        ,  estoqueTM,  clienteTM,  categoriaTM,  fornecedorTM,  funcionarioTM
            ,  caixaTM, funcLogado);
        
        config.setSize(310,340);
        config.setResizable(false);
        config.setLocationRelativeTo(null);
        config.setVisible(true);
    }//GEN-LAST:event_ConfigBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClienteAddBtn;
    private javax.swing.JLabel ClienteLabel;
    private javax.swing.JButton ClienteSearchBtn;
    private javax.swing.JTextField ClienteSearchTxtField;
    private javax.swing.JTable ClientesJTable;
    private javax.swing.JScrollPane ClientesScrollPane;
    private javax.swing.JButton ConfigBtn;
    private javax.swing.JButton EVendaBtn;
    private javax.swing.JButton FornecedorAddBtn;
    private javax.swing.JLabel FornecedorLabel;
    private javax.swing.JScrollPane FornecedorScrollPane;
    private javax.swing.JButton FornecedorSearchBtn;
    private javax.swing.JTextField FornecedorSearchTxtField;
    private javax.swing.JPanel Fornecedores;
    private javax.swing.JTable FornecedoresJTable;
    private javax.swing.JButton FuncionarioAddBtn;
    private javax.swing.JLabel FuncionarioLabel;
    private javax.swing.JButton FuncionarioSearchBtn;
    private javax.swing.JTextField FuncionarioSearchTxtField;
    private javax.swing.JTable FuncionariosJtable;
    private javax.swing.JScrollPane FuncionariosScrollPane;
    private javax.swing.JPanel FundoLogo;
    private javax.swing.JButton GerenciarCategoriaBtn;
    private javax.swing.JPanel JPClientes;
    private javax.swing.JPanel JPEstoque;
    private javax.swing.JPanel JPFuncionarios;
    private javax.swing.JPanel JPRelatorios;
    private javax.swing.JTabbedPane JanelaDeAbas;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JLabel ProdutoLabel;
    private javax.swing.JButton ProdutoSearchBtn;
    private javax.swing.JTextField ProdutoSearchTxtField;
    private javax.swing.JTable ProdutosJTable;
    private javax.swing.JScrollPane ProdutosScrollPane;
    private javax.swing.JButton RCompraBtn;
    private javax.swing.JTable RelatoriosJtable;
    private javax.swing.JScrollPane RelatoriosScrollPane;
    private javax.swing.JLabel SaldoLbl;
    private javax.swing.JLabel SaldoValue;
    private javax.swing.JLabel TabacariaTxt;
    // End of variables declaration//GEN-END:variables

    

    private void alterarProduto(int row) {
        FormularioProduto fp = new FormularioProduto(estoque.getItem(row), estoque, estoqueTM, categorias, 1);
        
    }

    private void addCliente() {
        Cliente cliente = new Cliente();
        
        FormularioCliente fc = new FormularioCliente(cliente, clientes, clienteTM, 0);
    }
    private void alterarCliente(int row) {
        FormularioCliente fp = new FormularioCliente(clientes.get(row), clientes, clienteTM, 1);
        
    }

    private void controleCategorias() {        
        ControleCategorias cc = new ControleCategorias( categorias, categoriaTM);
        cc.setSize(950,730);
        cc.setResizable(false);
        cc.setLocationRelativeTo(null);
        cc.setVisible(true);
    }
    
    private void novaOrdemVenda() throws CloneNotSupportedException {        
        Venda v = new Venda();
        VendaTableModel vendaTM = new VendaTableModel(v);
        FormularioVenda fv = new FormularioVenda( estoque, estoqueTM, v, vendaTM, clientes, caixa, caixaTM, SaldoValue, 0);
        fv.setSize(1200,900);
        fv.setResizable(false);
        fv.setLocationRelativeTo(null);
        fv.setVisible(true);
    }

    private void alterarFornecedor(int row) {
        FormularioFornecedor fc = new FormularioFornecedor(fornecedores.get(row), fornecedores, fornecedorTM, 1);
    }

    private void addFornecedor() {
        Fornecedor fornecedor = new Fornecedor();
        
        FormularioFornecedor fc = new FormularioFornecedor(fornecedor, fornecedores, fornecedorTM, 0);
    }

    private void addFuncionario() {
        Funcionario funcionario = new Funcionario();
        
        FormularioFuncionario ffunc = new FormularioFuncionario(funcionario, funcionarios, funcionarioTM, 0);
    }

    private void alterarFuncionario(int row) {
        FormularioFuncionario ffunc = new FormularioFuncionario(funcionarios.get(row), funcionarios, funcionarioTM, 1);
    }

    private void alterarTransacao(int row) throws CloneNotSupportedException {
        
        Transacao t = caixa.getFluxo().get(row);
        
        if(t instanceof Venda ) alteraVenda((Venda) t);
        if(t instanceof Compra) alteraCompra((Compra) t);
        
    }

    private void alteraVenda(Venda venda) throws CloneNotSupportedException {
        VendaTableModel vendaTM = new VendaTableModel(venda);
        FormularioVenda fv = new FormularioVenda( estoque, estoqueTM, venda, vendaTM, clientes, caixa, caixaTM, SaldoValue, 1);
        fv.setSize(1200,900);
        fv.setResizable(false);
        fv.setLocationRelativeTo(null);
        fv.setVisible(true);
    }

    private void alteraCompra(Compra compra) throws CloneNotSupportedException {
        CompraTableModel vendaTM = new CompraTableModel(compra);
        FormularioCompra fc = new FormularioCompra( estoque, estoqueTM, compra, vendaTM, fornecedores, caixa, caixaTM, SaldoValue, categorias, 1);
        fc.setSize(1200,900);
        fc.setResizable(false);
        fc.setLocationRelativeTo(null);
        fc.setVisible(true);
    }

    private void novaOrdemCompra() throws CloneNotSupportedException {
        Compra c = new Compra();
        CompraTableModel vendaTM = new CompraTableModel(c);
        FormularioCompra fc = new FormularioCompra( estoque, estoqueTM, c, vendaTM, fornecedores, caixa, caixaTM, SaldoValue, categorias, 0);
        fc.setSize(1200,900);
        fc.setResizable(false);
        fc.setLocationRelativeTo(null);
        fc.setVisible(true);
    }
    
    public Funcionario getFuncLogado() {
        return funcLogado;
    }

    //Funcionario Atual
    public void setFuncLogado(Funcionario funcLogado) {
        this.funcLogado = funcLogado;
        
        if(funcLogado.getAcesso() == 0)
            JanelaDeAbas.setEnabledAt(3,false);
    }
    
    
}
